---
title: "JCCG-LTFU Background factors"
author: "Mamiko Yonejima, Toshiki Saito"
output:
  word_document: default
  pdf_document:
    latex_engine: xelatex
  html_document: default
mainfont: Hiragino Kaku Gothic Pro
---
実行日時：`r Sys.time()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("./programs/make_ads.R", encoding = "UTF-8")
ads$base.date <- ads$fix.date
source("./programs/followup_rate.R", encoding = "UTF-8")
source("./programs/background_factors.R", encoding = "UTF-8")
```

##解析対象集団
```{r, echo=F}
nrow(ds.all02.bf.0)
```
##解析除外集団
```{r, echo=F}
nrow(missing.value.bf)
```
###解析除外集団の詳細・治療終了日不明
```{r, echo=F}
nrow(ds.all02.bf.0[ds.all02.bf.0$date.end.trt == "", ])
```
###解析除外集団の詳細・データ固定２年前以前に死亡した症例
```{r, echo=F}
nrow(ds.all02.bf.0[ds.all02.bf.0$no.death.before.2y ==F , ])
```

# ベースライン
##患者背景（データ固定２年前以前に死亡した症例、治療終了日不明を除いた患者集団の背景）
### 年齢（診断時）
```{r, echo=F}
age.diagnosis
```
### 性別
```{r, echo=F}
sex 
```
### 解析時年齢（データ固定時の年齢）
```{r, echo=F}
age.at.data.fixed
```
### 診断からの期間（診断～データ固定まで）
```{r, echo=F}
y.from.diagnosis
```
### マーカー
```{r, echo=F}
marker
```
### 初診時のWBC
```{r, echo=F}
initial.wbc
```
##除外集団の患者背景
### 年齢（診断時）
```{r, echo=F}
missing.value.age.diagnosis
```
### 性別
```{r, echo=F}
missing.value.sex
```
### 解析時年齢（データ固定時の年齢）
```{r, echo=F}
missing.value.age.at.data.fixed
```
### 診断からの期間（診断～データ固定まで）
```{r, echo=F}
missing.value.y.from.diagnosis
```
##追跡調査未提出の患者背景
### 年齢（診断時）
```{r, echo=F}
not.sbmt.fu.bf.age.diagnosis
```
### 性別
```{r, echo=F}
not.sbmt.fu.bf.sex
```
### 解析時年齢（データ固定時の年齢）
```{r, echo=F}
not.sbmt.fu.age.at.data.fixed
```
### 診断からの期間（診断～データ固定まで）
```{r, echo=F}
not.sbmt.fu.y.from.diagnosis
```


## 参加施設数
```{r, echo=F}
count.facilities
```


## 施設分類別症例登録数
```{r, echo=F}
number.by.facilities
```
